export {default as avatar} from './avatar.png';
export {default as female} from './female.png';
export {default as city} from './city.png';
export {default as date} from './date.png';
export {default as male} from './male.png';
export {default as language} from './language.png';
export {default as bg} from './bg.png';
export {default as user} from './user.png';
export {default as edit} from './edit.png';